[build-system]
requires = ["setuptools>=69", "wheel"]

[project]
name = "noteyourbusiness"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "PyQt6>=6.6",
  "cryptography>=42.0",
  "argon2-cffi>=23.1",
  "send2trash>=1.8",
]

[project.scripts]
nyb = "nyb.main:main"
